### ISSUE TITLE
baglantı sorunu

### ISSUE THREAD

**Issue by kissmorning** [kutsan/homebridge-cosa#1]
merhaba öncelikle eklenti için teşekkürler,raspberry cihaza kurulu homebridge var,ne yaptıysam yapılandırmayı yapamadım,bana yardımcı olurmusunuz,herhangi bir klavuz mevcutmu?

**Comment by kutsan** [comment]
Merhabalar, Cosa tarafında public stable bir API hizmeti henüz sunulmadığından ve bu nedenle plugin tam olarak stable seviyesine ulaşmadığından dokümantasyona bilerek kurulum aşamalarını eklemedim. Ufak bir API değişimi bile plugin'in çalışmamasına sebep olabilir. Üzerinde çalıştığım zaman stable olduğunu düşündüğümde public olarak açmayı ve README dosyasını ilgili şekilde güncellemeyi düşünüyorum.

Şu anda için fakat denemek isterseniz, Homebridge panel üzerinden config dosyasının `platforms` key'indeki array'a yeni bir item olarak Cosa platform'unu register edebilirsiniz. İleride bu aşama plugin yüklendikten sonra email/password girmenizi isteyen bir modal olarak sunulacaktır.

```json
{
    "bridge": {},
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "en",
            "platform": "config"
        },
        {
            "platform": "Cosa",
            "email": "you@example.com",
            "password": "your-password"
        }
    ]
}
```

**Comment by kissmorning** [comment]
tekrar merhaba config sorunsuz çalıştırdım fakat,mevcut homekit cihazlarıma ekleyince yanıt yok hatası alıyorum ama yeni ev ekle dediğimde sorunsuz kullanabiliyorum cosayı,sorun ne olabilir

**Comment by kissmorning** [comment]
merhaba,mevcut homekit cihazlarımın olduğu eve eklediğimde yanıt yok cevabı alıyorum,fakat yeni ev ekle dediğimde cosayı eklediğimde sorunsuz çalışıyor,bu durumu nasıl aşabiliriz?

**Comment by kutsan** [comment]
@kissmorning Yeni ev ekleme işini Home uygulaması üzerinden mi yapıyorsunuz yoksa Cosa uygulamasından mı? Homebridge'i yeniden başlatınca da sorun devam ediyor mu? Ayrıca Homebridge Logs kısmında plugin ile alakalı bir hata log'u görebiliyor musunuz?

**Comment by kissmorning** [comment]
merhaba telefonun ev uygulamasından yapıyorum,homebridge raspberry pi ile çalışıyor,yeniden başlatınca düzelmiyor.

log:
[4/11/2024, 10:54:56 AM] [homebridge-cosa] This plugin slows down Homebridge. The read handler for the characteristic 'Target Temperature' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[4/11/2024, 10:54:38 AM] [Config] Cosa platform finished initializing!
[4/11/2024, 10:54:51 AM] [Config] Logged in 61e6cbd196b78f8d7f47ca39.
[4/11/2024, 10:54:51 AM] [Config] Thermostat finished initializing!
[4/11/2024, 10:54:51 AM] Initializing platform accessory 'Cosa Thermostat'...
Setup Payload:
X-HM://0024X4W9G76SV

**Comment by kissmorning** [comment]
yapılandırmam bu şekilde yanlış varmı?

{
    "bridge": {
        "name": "Homebridge B89A",
        "username": "0E:64:1E:B8:B8:9A",
        "port": 51131,
        "pin": "876-81-318",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "Cosa",
            "email": "abcd@gmail.com",
            "password": "12345678"
        },
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}

**Comment by kutsan** [comment]
Selamlar tekrardan, kusura bakmayın iş yoğunluğundan dolayı cevap veremedim. Yolladığınız config'de bir sorun görünmüyor fakat reproduce edebilmem için birkaç soru daha sormak istiyorum. HomeKit cihazlarınızın bulunduğu evde varsa Homebridge'deki diğer cihazlarınız bir sorun olmadan görünüyor mu? Ev ayarlarından Homebridge'in bridges kısmında ekli olduğunu doğrulayabilir misiniz? Belki HomeKit cihazlarınızın bulunduğu evde Homebridge kayıtlı bir bridge olarak görünmüyor olabilir.
